### ISSUE TITLE
Server Exits with code 255 with no activity

### ISSUE THREAD

**Issue by shaqaruden** [beyondcode/laravel-websockets#1025]
I have noticed that if I run the server and no clients are pinging it, it will exit after some amount of time with the error status code of 255. There's nothing in the log other than the last request made.
![image](https://user-images.githubusercontent.com/5414897/186895130-c8a7f4bb-c000-4a26-a1d5-471f0c8d2de6.png)

I am using it within my docker environment here is my service definition for it

```yml
services:
  ...

    websockets:
      image: php:8.1-fpm-alpine
      volumes:
        - ./web:/var/www/html:delegated
        - ./logs:/var/www/logs
      working_dir: /var/www/html
      expose: [6001]
      labels:
        caddy: staging.h1.listech.on.ca
        caddy.@ws.0_header: "Connection *Upgrade*"
        caddy.@ws.1_header: "Upgrade websocket"
        caddy.reverse_proxy: "@ws {{upstreams 6001}}"
      entrypoint: ["php", "/var/www/html/artisan", "websockets:serve"]
      networks:
        - routable
        - h1project
```
