### ISSUE TITLE
Unable to connect to localhost:6001/laravel-websockets api when running websockets in docker

### ISSUE THREAD

**Issue by pragya-mishra-cyble-dev** [beyondcode/laravel-websockets#1145]
I have created a separate container for websockets with port 6001 open.
This is my docker config - 
 ```
 websocket:
      build:
          context: .
          dockerfile: compose/dev/php/Dockerfile
      container_name: websocket
      restart: unless-stopped
      command: "php artisan websockets:serve --host=127.0.0.1 --port=6001"
      volumes:
          - ./:/var/www/html
      working_dir: /var/www/html
      ports:
          - "6001:6001"
      expose:
          - "6001"
      networks:
          - laravel
      depends_on:
          - mysql
          - php
          - redis
```

However I am able to connect to - 
ws://localhost:6001/app/notifications

I can send messages but they do not seem to be reaching anywhere

Additionally even while sending notifications from tinker I am getting PendingBroadcast only
Can someone help?
