### ISSUE TITLE
How to use it with nginx reverse proxy on google app engine on port 443

### ISSUE THREAD

**Issue by ibrunotome** [beyondcode/laravel-websockets#159]
I'm trying to deploy it into a google app engine service and don't manage ssl certificates. App engine "google frontend" will only forward port 80 and 443 to the custom user nginx.conf file that listen in port 8080. So after deployed there is no erros and the google stackdriver logs show me that the websocket service is accepting connections, but the frontend service don't show me anything, no erros and no success. So what I'm missing?

Currently nginx.conf for this service is:

```
daemon off;

user  root;
worker_processes  auto;
error_log /dev/stderr info;

events {
    worker_connections  4096;
}

http {
    access_log /dev/stdout;

    server {
        listen 8080;
        
        location / {
            proxy_pass             http://127.0.0.1:6001;
            proxy_read_timeout     60;
            proxy_connect_timeout  60;
            proxy_redirect         off;

            # Allow the use of websockets
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
```

and my app.yaml file:

```
runtime: custom
env: flex

service: websockets

manual_scaling:
  instances: 1

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

runtime_config:
  document_root: public
  enable_stackdriver_integration: true

readiness_check:
  app_start_timeout_sec: 1800

env_variables:
  // all basic laravel env here plus:

  BROADCAST_DRIVER: pusher

  PUSHER_APP_ID: testing
  PUSHER_APP_KEY: testing
  PUSHER_APP_SECRET: testing
```

My pusher config in broadcast.php file is

```php
'pusher' => [
    'driver'  => 'pusher',
    'key'     => env('PUSHER_APP_KEY'),
    'secret'  => env('PUSHER_APP_SECRET'),
    'app_id'  => env('PUSHER_APP_ID'),
    'options' => [
        'host'      => 'my-websockets-service-generated-domain.appspot.com',
        'port'      => '443',
        'scheme'    => 'https',
        'encrypted' => true
    ],
],
```

And finally my settings on the client side:

```javascript
window.Pusher = require('pusher-js')

const echo = new Echo({
  authEndpoint: 'my-backend-service-generated-domain.appspot.com/broadcasting/auth',
  broadcaster: 'pusher',
  key: 'testing',
  httpHost: 'my-websockets-service-generated-domain.appspot.com',
  httpsPort: 443,
  disableStats: true,
  encrypted: true
})
```

The google stackdriver logs:

[![google stackdriver logs][1]][1]

  [1]: https://i.stack.imgur.com/mesFY.png
