### ISSUE TITLE
Server Setup

### ISSUE THREAD

**Issue by rjvim** [beyondcode/laravel-websockets#182]
In Documentation: https://docs.beyondco.de/laravel-websockets/1.0/faq/scaling.html

You were able to achieve:
"Here is another benchmark that was run on a 2GB Digital Ocean droplet with 2 CPUs. The maximum number of concurrent connections on this server setup is nearly 60,000"

I have tried with same server configuration on DO with Ubuntu.

I tested with Artillery:

```
config:
  target: "wss://rtc.xxx.com:443/app/websocketkey?protocol=7&client=js&version=4.4.0&flash=false"
  phases:
    - duration: 120
      arrivalRate: 40
      rampTo: 40
      name: "Ramping up the load"
scenarios:
  - engine: "ws"
    flow:
      - send: '{"event":"pusher:subscribe","data":{"channel":"public"}}'
      - think: 15
```

On server I am using nginx with reverse proxy (https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html#usage-with-a-reverse-proxy-like-nginx)

The server is created using forge, so I run `php artisan websockets:serve` using Daemon.

I have increased number of file descriptors. I have installed pecl event.

When I run artillery, I get max of 600 concurrent users. If I increase arrivalRate to more than 40, I get errors like:

```
  Scenarios launched:  0
  Scenarios completed: 603
  Requests completed:  0
  RPS sent: NaN
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
```

Is there anything I am missing, which is not giving me similar performance?
