### ISSUE TITLE
how do you test the max connection that success? 

### ISSUE THREAD

**Issue by erlangp** [beyondcode/laravel-websockets#437]
https://beyondco.de/docs/laravel-websockets/faq/scaling
how do you test the max connection that success?

**Comment by edvordo** [comment]
Not sure about a proper way to do this, but I tested this the help of couple of friends using https://artillery.io/ with following config `test-ws.yaml` 
```yaml
config:
  target: "wss://ws.example.com/app/yourPusherAppKey?protocol=7&client=js&version=4.3.1&flash=false"
  phases:
    - duration: 600
      arrivalRate: 10
      name: "Ramping up the load"
scenarios:
- engine: "ws"
  flow:
    - loop:
      - think: 29 # pusher expect ping event every 30 seconds or it disconnects the client
      - send: '{"event":"pusher:ping","data":{}}'
```
We each got a copy of the above script and just let it run. I monitored the server from my end to see how many connections it allowed. We ended testing when we were able to reach around 7000 or 8000 concurrent connection, which was enough for our needs, but there is not reason to doubt it would support many more
