### ISSUE TITLE
Stability of ws Server when under load?

### ISSUE THREAD

**Issue by zhiyong80** [beyondcode/laravel-websockets#521]
Hi,

My test server stopped working after about 5 hours with 10K concurrent active connections. Could anybody offer some pointers on how to optimize system and increase system robustness?

The test server is running on an old laptop(I5-3320m + 16GB ram + SSD), with Ubuntu 18.04, php7.2 with libevent-dev, event and ev extension installed, and the latest Rechaet package.

Load test is done with the following Artillery settings:

```
  config:
    target: "ws://10.1.10.38:8080"
    phases:
      - duration: 1000
        arrivalRate: 10
    ws:
      # Ignore SSL certificate errors
      # - useful in *development* with self-signed certs
      rejectUnauthorized: false
  scenarios:
    - engine: "ws"
      flow:
        - loop:
          - send: "hello"
          - think: 28
```
When the load test is running, one of CPU cores as shown in system monitor occasionally reaches 100% once in a while, while the rest 3 stay less than 10%, and memory usage is less than 3GB. So I don't think resource limitation is not a problem.
