### ISSUE TITLE
Web socket connection error when application running in laravel/sail

### ISSUE THREAD

**Issue by sanjitkung** [beyondcode/laravel-websockets#655]
I am running a fresh instance of Laravel application using sail

After installing websockets package when I try to access sockets dashboard, I get an error 

![image](https://user-images.githubusercontent.com/9400880/104136009-85ffd080-5361-11eb-834e-1d461d42e9a0.png)

I try to map the container port but no luck

```yml
...
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
            - '6001:6001'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
...
```
