### ISSUE TITLE
[Docs] Port forwarding with Laravel Sail

### ISSUE THREAD

**Issue by wirk** [beyondcode/laravel-websockets#693]
it took me a while to figure out I needed to add a port forward in order to use laravel-websockets locally with sail. Maybe you could add this info to the documentation?

For anyone else with the same problem, here is my config:
```yaml
# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
            - '${LARAVEL_WEBSOCKETS_PORT:-6001}:${LARAVEL_WEBSOCKETS_PORT:-6001}'
```
