### ISSUE TITLE
Help Wanted, I cannot connect to SSL on server with Docker and Nginx.

### ISSUE THREAD

**Issue by RyanDaDeng** [beyondcode/laravel-websockets#878]
I have searched a lot documents and tried many methods but still no luck.

in my nginx error log file i get:

``
 upstream prematurely closed connection while reading response header from upstream,
``

My app and websocket are all in dockers, so i have to proxy 443 to docker container 6001 port through nginx file.

my docker-compose file:

````
  websocket:
    build:
      args:
        user: ryan
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: app-websocket
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 6001:6001
    volumes:
      - ./:/var/www
    entrypoint: [ "php", "artisan", "websocket:serve" ]
    networks:
      - app
````

my nginx setting:

````
server{    
listen 80;
    server_name xxx;
    location / {
        return 301 https://$host$request_uri;
    }
}


  upstream websocket {
    server websocket:6001;
  }

server {
listen 443 ssl http2;
listen [::]:443 ssl http2;

server_name xxx;
ssl_certificate /etc/letsencrypt/live/xxx/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/xxx/privkey.pem;
include /etc/letsencrypt/options-ssl-nginx.conf;
ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/public;




    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        root /var/www/certbot;
    }



    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    location /app/ {
        proxy_pass             http://websocket:6001;
        proxy_read_timeout     60;
        proxy_connect_timeout  60;
        proxy_redirect         off;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
     }


}
````

websockets.php config file:

````
    'dashboard' => [

        'port' => env('LARAVEL_WEBSOCKETS_PORT', 443),  // i make it as 443

        'domain' => env('LARAVEL_WEBSOCKETS_DOMAIN'), // my url is correct

        'path' => env('LARAVEL_WEBSOCKETS_PATH', 'laravel-websockets'),

        'middleware' => [
            'web',
            \BeyondCode\LaravelWebSockets\Dashboard\Http\Middleware\Authorize::class,
        ],

    ],

````

![image](https://user-images.githubusercontent.com/37111049/139205856-af0be13f-23be-4e59-887c-164d90fc8505.png)

Do I miss anything?

Thanks in advance!
